version: "3"

services:
  nginx:
    image: nginx:1.17
    ports:
      - "8010:80"
    volumes:
      - ./:/src
      - ./contrib/local.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-fpm
  php-fpm:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - proxy-service-mysql
    volumes:
      - ./public:/src/public
      - ./app:/src/app
      - ./start-php-fpm.sh:/app/src/start-php-fpm.sh
      - ./bootstrap/app.php:/src/bootstrap/app.php
      - ./config:/src/config
      - ./database:/src/database
      - ./lang:/src/lang
      - ./resources:/src/resources
      - ./routes:/src/routes
      - ./tests:/src/tests
      - ./storage:/src/storage
      - ./composer.json:/src/composer.json
      - ./composer.lock:/src/composer.lock
      - ./.env:/src/.env
  proxy-service-mysql:
    image: "mysql:5"
    ports:
      - "33033:3306"
    environment:
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: supersecret